emotes-menu:
  title: "Emotes - Menu"
  emotes-slots:
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
  items:
    border:
      material: BLACK_STAINED_GLASS_PANE
      display-name: "&f "
      slots:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 45
        - 46
        - 47
        - 48
        - 49
        - 50
        - 51
        - 52
        - 53